package gui;


import controller.DataBaseConnection;
import controller.PopulateTable;
import controller.IconSetter;
import controller.PopulateCombobox;
import controller.ManageBook;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Necil Dabre, Preet Dabre, Glen Dabre, Chris Carvalho
 */
public class BookFrame extends javax.swing.JFrame {
private String sql= null;
private Connection con = null;
    /**
     * Creates new form BookFrame
     */
    public void resetInsertForm(){
        bookidTf.setText("");
        booknameTf.setText("");
        isbnTf.setText("");
        editionTf.setText("");
        authorTf.setText("");
        categoryJComboBox.setSelectedIndex(0);
        nopTf.setText("");
        addShelfNo.setSelectedIndex(0);
        availJComboBox.setSelectedIndex(0);

    }
    public void resetUpdateForm(){
                updateBookIdLabel.setText("");
                updateBookNameTf.setText("");
                updaeISBNTf.setText("");
                updateAuthorTf.setText("");
                updateEditionTf.setText("");
                updateNopTF.setText("");
                UpdateshelfJComboBox.setSelectedIndex(0);
                updateCategoryComboBox.setSelectedIndex(0);
                updateBookidTf.setText("");
    }
    public void updateCombo(){

        //set combobox
        sql = "SELECT shelfno from shelf";
        PopulateCombobox.setComboBox(con, addShelfNo, sql, "shelfno");
        PopulateCombobox.setComboBox(con, DeleteShelf, sql, "shelfno");
        PopulateCombobox.setComboBox(con, UpdateshelfJComboBox, sql, "shelfno");
        
        sql = "Select name from category order by name asc";
        PopulateCombobox.setComboBox(con, categoryJComboBox, sql, "name");
        PopulateCombobox.setComboBox(con, updateCategoryComboBox, sql, "name");
    }
    
    public void updateTable(){
        
        //set the tables
        sql = "SELECT bookid as BookID, bookname as Name, isbn as ISBN, edition as Edition, authorname as Author, catid as Category, nop as Pages, shelfno as Shelf, avialable as Available FROM  books";
        PopulateTable.setTable(con,BookTable, sql);
        
        sql = "SELECT shelfno as ShelfID,location as Location FROM shelf";
        PopulateTable.setTable(con,Shelf, sql);
    }
    
    
    public boolean checkFields(){
        int flag = 1;
        String message = "";
        
        if(bookidTf.getText().length() <  13 || bookidTf.getText().length() >  13){
            flag =0;
            message +="Enter A Valid BookId \n";
        }
        
        if(booknameTf.getText().isEmpty()){
            flag = 0;
            message +="Enter A Valid Book Name\n";
        }
        if(isbnTf.getText().isEmpty()){
            flag = 0;
            message +="Enter A Valid ISBN\n";
        }
        if(authorTf.getText().isEmpty()){
            flag = 0;
            message +="Enter A Valid Author Name\n";
        }
        if(editionTf.getText().isEmpty()){
            flag = 0;
            message +="Enter A Valid Edition \n";
        }
        if(nopTf.getText().isEmpty() ){
            flag = 0;
            message +="Enter A Valid Pages\n";
        }
        if(flag == 1){
            return true;
        }
        JOptionPane.showMessageDialog(null ,message, "Input Error", ERROR_MESSAGE);
        return false;
    }
    public BookFrame() {
        initComponents();
        IconSetter.setIcon(this);
        con = DataBaseConnection.getConnection();
       updateTable();
        updateCombo();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        insertBookBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        editionTf = new javax.swing.JTextField();
        nopTf = new javax.swing.JTextField();
        isbnTf = new javax.swing.JTextField();
        authorTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        availJComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        categoryJComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        booknameTf = new javax.swing.JTextField();
        bookidTf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        addShelfNo = new javax.swing.JComboBox();
        checkBookIdBtn = new javax.swing.JButton();
        generateBookIdBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        refreshbtn = new javax.swing.JButton();
        searchBookbtn = new javax.swing.JButton();
        searchBookTf = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        updateAuthorTf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        updateEditionTf = new javax.swing.JTextField();
        updateNopTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        updateCategoryComboBox = new javax.swing.JComboBox();
        updateBookBtn = new javax.swing.JButton();
        deleteBookBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        updateBookNameTf = new javax.swing.JTextField();
        UpdateshelfJComboBox = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        updaeISBNTf = new javax.swing.JTextField();
        updateBookIdLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        upadateLookupBtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        updateBookidTf = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        addShelfnoTf = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        addLocationTf = new javax.swing.JTextField();
        addShelfBtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Shelf = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        DeleteShelf = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        deleteShelf = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        updateShelfNoJlabel = new javax.swing.JLabel();
        updateShelfLocation = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        updateShelfBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Books -Library Management System");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Book Management", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 18))); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Book Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 18))); // NOI18N

        insertBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/insert16.png"))); // NOI18N
        insertBookBtn.setText("Insert Book");
        insertBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBookBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Book Name");

        jLabel5.setText("Author Name");

        jLabel4.setText("Edition");

        nopTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopTfActionPerformed(evt);
            }
        });

        jLabel3.setText("ISBN");

        availJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));

        jLabel7.setText("No of Pages");

        jLabel6.setText("Category");

        jLabel1.setText("Book Id");

        jLabel8.setText("Availability");

        booknameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booknameTfActionPerformed(evt);
            }
        });

        jLabel16.setText("Shelf No");

        checkBookIdBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lookupbook16.png"))); // NOI18N
        checkBookIdBtn.setText("Check Book Id");
        checkBookIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBookIdBtnActionPerformed(evt);
            }
        });

        generateBookIdBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/issusebook16.png"))); // NOI18N
        generateBookIdBtn.setText("Generate Bookid");
        generateBookIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBookIdBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(isbnTf, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookidTf, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(booknameTf, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editionTf, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkBookIdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generateBookIdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(availJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(nopTf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addShelfNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(categoryJComboBox, 0, 201, Short.MAX_VALUE)
                            .addComponent(authorTf))
                        .addContainerGap())))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(insertBookBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(bookidTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBookIdBtn))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(booknameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(categoryJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(isbnTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(nopTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(addShelfNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(editionTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(availJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(generateBookIdBtn)))
                .addGap(52, 52, 52)
                .addComponent(insertBookBtn)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Book", jPanel2);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 3, 18))); // NOI18N

        refreshbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh16.png"))); // NOI18N
        refreshbtn.setText("Refresh Table");
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });

        searchBookbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search16.png"))); // NOI18N
        searchBookbtn.setText("Search");
        searchBookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBookbtnActionPerformed(evt);
            }
        });

        searchBookTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchBookTfKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(searchBookbtn)
                        .addGap(18, 18, 18)
                        .addComponent(refreshbtn))
                    .addComponent(searchBookTf, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchBookTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBookbtn)
                    .addComponent(refreshbtn))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 3, 18))); // NOI18N

        BookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(BookTable);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Book", jPanel3);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Book Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 18))); // NOI18N

        updateAuthorTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAuthorTfActionPerformed(evt);
            }
        });

        jLabel9.setText("Book Id");

        jLabel17.setText("Shelf Number");

        jLabel13.setText("Author Name");

        jLabel10.setText("Book Name");

        jLabel11.setText("ISBN");

        jLabel12.setText("Edition");

        updateBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/updatebtn16.png"))); // NOI18N
        updateBookBtn.setText("Update");
        updateBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBookBtnActionPerformed(evt);
            }
        });

        deleteBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close16.png"))); // NOI18N
        deleteBookBtn.setText("Delete");
        deleteBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookBtnActionPerformed(evt);
            }
        });

        jLabel15.setText("No of Pages");

        jLabel14.setText("Category");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(updateBookBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateBookIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateEditionTf)
                                    .addComponent(updaeISBNTf, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(updateBookNameTf)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(deleteBookBtn))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(UpdateshelfJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateNopTF, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateCategoryComboBox, 0, 148, Short.MAX_VALUE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(updateAuthorTf)))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(updateAuthorTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(updateBookIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(updateBookNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(updateCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(updaeISBNTf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(updateNopTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(updateEditionTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(UpdateshelfJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBookBtn)
                    .addComponent(deleteBookBtn))
                .addGap(19, 19, 19))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 18))); // NOI18N

        upadateLookupBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lookupbook16.png"))); // NOI18N
        upadateLookupBtn.setText("Look Up");
        upadateLookupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upadateLookupBtnActionPerformed(evt);
            }
        });

        jLabel18.setText("Book ID");

        updateBookidTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateBookidTfKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateBookidTf, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upadateLookupBtn))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(updateBookidTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(upadateLookupBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update/Delete Book", jPanel4);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Shelf", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14))); // NOI18N

        addShelfnoTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShelfnoTfActionPerformed(evt);
            }
        });

        jLabel19.setText("Shelf No");

        addShelfBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/insert16.png"))); // NOI18N
        addShelfBtn.setText("Add");
        addShelfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShelfBtnActionPerformed(evt);
            }
        });

        jLabel20.setText("Location");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addShelfBtn)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(addLocationTf, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(addShelfnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(addShelfnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(addLocationTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addShelfBtn)
                .addContainerGap())
        );

        Shelf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Shelf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShelfMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Shelf);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete Shelf", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14))); // NOI18N

        jLabel21.setText("Shelf No");

        deleteShelf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close16.png"))); // NOI18N
        deleteShelf.setText("Delete");
        deleteShelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteShelfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteShelf, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deleteShelf))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(DeleteShelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteShelf)
                .addContainerGap())
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 3, 14))); // NOI18N

        jLabel22.setText("Shelf No");

        jLabel24.setText("Location");

        updateShelfBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/updatebtn16.png"))); // NOI18N
        updateShelfBtn.setText("Update");
        updateShelfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateShelfBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateShelfNoJlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateShelfLocation))
                .addContainerGap())
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(updateShelfBtn)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(updateShelfNoJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(updateShelfLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateShelfBtn)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(117, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Add/Delete Shelf", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        new AdminFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void updateShelfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateShelfBtnActionPerformed
        // TODO add your handling code here:
        if(!updateShelfNoJlabel.getText().equals("")){
            if(!updateShelfLocation.getText().equals("")){
                if( ManageBook.updateShelf(con,updateShelfNoJlabel.getText() , updateShelfLocation.getText()) )
                {
                    updateTable();
                    updateShelfNoJlabel.setText("");
                    updateShelfLocation.setText("");
                    JOptionPane.showMessageDialog(null, "Shelf Updated Successfully","Shelf Updated",INFORMATION_MESSAGE);
                }
                else{

                    JOptionPane.showMessageDialog(null, "Shelf  Not Updated","Shelf Updated",INFORMATION_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "The Location Field cannot be Blank","Shelf", ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Select a Valid Shelf No","Shelf Error",ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateShelfBtnActionPerformed

    private void deleteShelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteShelfActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Do you really want to delete shelf "+DeleteShelf.getSelectedItem(),"Delete Shelf", YES_NO_OPTION,QUESTION_MESSAGE) == 0){

            if( !ManageBook.checkShelfBeforeDelete(con,DeleteShelf.getSelectedItem().toString())){

                if(ManageBook.deleteShelf(con, DeleteShelf.getSelectedItem().toString())){
                    updateTable();
                    updateCombo();
                    JOptionPane.showMessageDialog(null, "Shelf  Deleted Sucessfully","Delete Shelf Notificaion",INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Shelf not Deleted","Delete Shelf Notification",ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Shelf cannot be deleted because it has some books","Delete Shelf Notification",WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteShelfActionPerformed

    private void ShelfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShelfMouseClicked
        // TODO add your handling code here:
        try {
            int row = Shelf.getSelectedRow();
            String bookid = (Shelf.getModel().getValueAt(row,0)).toString();
            ResultSet rs = ManageBook.getShelfDetails(con, bookid);
            while(rs.next()){
                updateShelfNoJlabel.setText(rs.getString("shelfno"));
                updateShelfLocation.setText(rs.getString("location"));
            }
        } catch (Exception e) {
            System.out.println("Table Exception "+e);
        }
    }//GEN-LAST:event_ShelfMouseClicked

    private void addShelfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShelfBtnActionPerformed
        // TODO add your handling code here:
        if( !(addShelfnoTf.getText().equals("")) && !(addLocationTf.getText().equals("")) ){
            if(ManageBook.checkShelf(con,addShelfnoTf.getText() )){

                if(ManageBook.insertShelf(con, addShelfnoTf.getText(), addLocationTf.getText())){
                    updateTable();
                    updateCombo();
                    JOptionPane.showMessageDialog(null, "Shelf Inserted Successfully","Insert Shelf Notificaion",INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Shelf Not Inserted","Insert Shelf Notificaion",ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Shelf number already added ","Insert Shelf Notificaion",ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Both fields cannot be empty","Insert Shelf Notificaion",INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_addShelfBtnActionPerformed

    private void addShelfnoTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShelfnoTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addShelfnoTfActionPerformed

    private void updateBookidTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateBookidTfKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                ResultSet rs = ManageBook.getBookInfo(con,updateBookidTf.getText());
                if(rs.next()){
                    updateBookIdLabel.setText(rs.getString("bookid"));
                    updateBookNameTf.setText(rs.getString("bookname"));
                    updaeISBNTf.setText(rs.getString("isbn"));
                    updateAuthorTf.setText(rs.getString("authorname"));
                    updateEditionTf.setText(rs.getString("edition"));
                    updateNopTF.setText(""+rs.getInt("nop"));
                    UpdateshelfJComboBox.setSelectedItem(rs.getString("shelfno"));
                    updateCategoryComboBox.setSelectedItem(rs.getString("catid"));
                }
                else{
                    resetUpdateForm();
                    JOptionPane.showMessageDialog(null,"No such Book id Exists","Book Notification",WARNING_MESSAGE);
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_updateBookidTfKeyPressed

    private void upadateLookupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upadateLookupBtnActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = ManageBook.getBookInfo(con,updateBookidTf.getText());
            if(rs.next()){
                updateBookIdLabel.setText(rs.getString("bookid"));
                updateBookNameTf.setText(rs.getString("bookname"));
                updaeISBNTf.setText(rs.getString("isbn"));
                updateAuthorTf.setText(rs.getString("authorname"));
                updateEditionTf.setText(rs.getString("edition"));
                updateNopTF.setText(""+rs.getInt("nop"));
                UpdateshelfJComboBox.setSelectedItem(rs.getString("shelfno"));
                updateCategoryComboBox.setSelectedItem(rs.getString("catid"));
            }
            else{
                JOptionPane.showMessageDialog(null,"No such Book id Exists","Book Notification",WARNING_MESSAGE);
                resetUpdateForm();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_upadateLookupBtnActionPerformed

    private void deleteBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookBtnActionPerformed
        // TODO add your handling code here:
        if(!updateBookIdLabel.getText().equals("")){
            String msg = "Do you want to delete record of book id "+ updateBookIdLabel.getText();
            if(JOptionPane.showConfirmDialog(null, msg) == 0){
                if(ManageBook.isIssused(con, msg)){
                    JOptionPane.showMessageDialog(null, "Book Cannot be Deleted","Book Notification",ERROR_MESSAGE);
                    return;
                }
                if(ManageBook.delete(con, updateBookIdLabel.getText())){
                    JOptionPane.showMessageDialog(null, "Data Deleted Successfully","Book Notification",INFORMATION_MESSAGE);
                    updateTable();
                    resetUpdateForm();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Data Not Deleted","Book Notification",WARNING_MESSAGE);
                }
            }

        }
        else{
            JOptionPane.showMessageDialog(null, "Enter a valid Book id","Book Notification",ERROR_MESSAGE);

        }
    }//GEN-LAST:event_deleteBookBtnActionPerformed

    private void updateBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBookBtnActionPerformed
        // TODO add your handling code here:
        if(!updateBookIdLabel.getText().equals("")){
            ArrayList al = new ArrayList();
            al.add(updateBookNameTf.getText());
            al.add(1,updaeISBNTf.getText());
            al.add(2,updateEditionTf.getText());
            al.add(3,updateAuthorTf.getText());
            al.add(4,updateCategoryComboBox.getSelectedItem());
            al.add(5,updateNopTF.getText());
            al.add(6,UpdateshelfJComboBox.getSelectedItem());
            al.add(7,updateBookIdLabel.getText());

            if(ManageBook.updateBook(con,al)){
                JOptionPane.showMessageDialog(null, "Data Update Successfully","Book Notification",INFORMATION_MESSAGE);
                updateTable();
            }
            else{
                JOptionPane.showMessageDialog(null, "Data Not Updated","Book Notification",WARNING_MESSAGE);
            }

        }
        else{
            JOptionPane.showMessageDialog(null, "Enter a valid Book id","Book Notification",ERROR_MESSAGE);
            resetUpdateForm();

        }
    }//GEN-LAST:event_updateBookBtnActionPerformed

    private void updateAuthorTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAuthorTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateAuthorTfActionPerformed

    private void searchBookTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBookTfKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!searchBookTf.getText().equals("")){
                ResultSet rs = ManageBook.searchBook(con, searchBookTf.getText());

                if(!(rs == null))
                PopulateTable.setTable(BookTable, rs);
            }
        }
        if(evt.getKeyCode() == KeyEvent.VK_F5){
            updateTable();
        }
    }//GEN-LAST:event_searchBookTfKeyPressed

    private void searchBookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBookbtnActionPerformed
        // TODO add your handling code here:
        if(!searchBookTf.getText().equals("")){
            System.out.println(""+searchBookTf.getText());
            ResultSet rs = ManageBook.searchBook(con, searchBookTf.getText());

            if(!(rs == null))
            PopulateTable.setTable(BookTable, rs);
        }
    }//GEN-LAST:event_searchBookbtnActionPerformed

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        // TODO add your handling code here:
        updateTable();
    }//GEN-LAST:event_refreshbtnActionPerformed

    private void generateBookIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBookIdBtnActionPerformed
        // TODO add your handling code here:
        bookidTf.setText(ManageBook.generateBookID(con));
    }//GEN-LAST:event_generateBookIdBtnActionPerformed

    private void checkBookIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBookIdBtnActionPerformed
        // TODO add your handling code here:
        if(bookidTf.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Book Id cannot be Empty","Book Notification",WARNING_MESSAGE);
            return;
        }
        if(bookidTf.getText().length() < 13  || bookidTf.getText().length() > 13){

            JOptionPane.showMessageDialog(null, "Enter A Valid Book ID","Book Notification",WARNING_MESSAGE);
            return;
        }
        if(ManageBook.check(con, bookidTf.getText())){

            JOptionPane.showMessageDialog(null, "Book Id Does not Exits","Book Notification",WARNING_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "Book Id Already Exits","Book Notification",WARNING_MESSAGE);
        }
    }//GEN-LAST:event_checkBookIdBtnActionPerformed

    private void booknameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booknameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booknameTfActionPerformed

    private void nopTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nopTfActionPerformed

    private void insertBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBookBtnActionPerformed
        // TODO add your handling code here:
        if(checkFields()){
            if(ManageBook.check(con, bookidTf.getText())){
                ArrayList al = new ArrayList();
                //storing data in arraylist for insertion
                al.add(bookidTf.getText());
                al.add(1,booknameTf.getText());
                al.add(2,isbnTf.getText());
                al.add(3,editionTf.getText());
                al.add(4,authorTf.getText());
                al.add(5,categoryJComboBox.getSelectedItem());
                al.add(6,nopTf.getText());
                al.add(7,addShelfNo.getSelectedItem());
                al.add(8,availJComboBox.getSelectedItem());

                if( ManageBook.insertBook(con, al) ){
                    resetInsertForm();
                    JOptionPane.showMessageDialog(null,"Data  Inserted","Book",JOptionPane.INFORMATION_MESSAGE);
                    updateTable();

                }
                else{
                    JOptionPane.showMessageDialog(null,"Data Not Inserted","Book",JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Book Id already Exists","Book",JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_insertBookBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BookTable;
    private javax.swing.JComboBox DeleteShelf;
    private javax.swing.JTable Shelf;
    private javax.swing.JComboBox UpdateshelfJComboBox;
    private javax.swing.JTextField addLocationTf;
    private javax.swing.JButton addShelfBtn;
    private javax.swing.JComboBox addShelfNo;
    private javax.swing.JTextField addShelfnoTf;
    private javax.swing.JTextField authorTf;
    private javax.swing.JComboBox availJComboBox;
    private javax.swing.JTextField bookidTf;
    private javax.swing.JTextField booknameTf;
    private javax.swing.JComboBox categoryJComboBox;
    private javax.swing.JButton checkBookIdBtn;
    private javax.swing.JButton deleteBookBtn;
    private javax.swing.JButton deleteShelf;
    private javax.swing.JTextField editionTf;
    private javax.swing.JButton generateBookIdBtn;
    private javax.swing.JButton insertBookBtn;
    private javax.swing.JTextField isbnTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nopTf;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JTextField searchBookTf;
    private javax.swing.JButton searchBookbtn;
    private javax.swing.JButton upadateLookupBtn;
    private javax.swing.JTextField updaeISBNTf;
    private javax.swing.JTextField updateAuthorTf;
    private javax.swing.JButton updateBookBtn;
    private javax.swing.JLabel updateBookIdLabel;
    private javax.swing.JTextField updateBookNameTf;
    private javax.swing.JTextField updateBookidTf;
    private javax.swing.JComboBox updateCategoryComboBox;
    private javax.swing.JTextField updateEditionTf;
    private javax.swing.JTextField updateNopTF;
    private javax.swing.JButton updateShelfBtn;
    private javax.swing.JTextField updateShelfLocation;
    private javax.swing.JLabel updateShelfNoJlabel;
    // End of variables declaration//GEN-END:variables
}
