package gui;


import controller.DataBaseConnection;
import controller.IconSetter;
import controller.PopulateTable;
import controller.ManageBorrow;
import controller.ManageBook;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Necil Dabre, Preet Dabre, Glen Dabre, Chris Carvalho
 */
public class BorrowBookFrame extends javax.swing.JFrame {
private String sql= null;
private Connection con = null;
    /**
     * Creates new form BorrowBookFrame
     */
public void updateBorrowerTable(){
    
              PopulateTable.setTable(con, BorrowerJtable, "select * from books_borrowed");
}
public void resetReturnForm(){
    returnBookId.setText("");
     returnBooknameTF.setText("");
     returnBookEditionTf.setText("");
     returnBorrowerIdTF.setText("");
     returnBorrowerNameTf.setText("");
    ((JTextField)(returnissuseDate.getDateEditor().getUiComponent())).setText("");
    ((JTextField)(returnDate.getDateEditor().getUiComponent())).setText("");
}
public void resetBorrowForm(){
       borrowBookidTf.setText("");
       borrowBookNameTf.setText("");
       borrowAuthorTf.setText("");
       borrowEditionTf.setText("");
       borrowerIdTf.setText("");
       borrowerNameTf.setText("");
       sql = "select bid as IssuseId,b.bookid as BookID,b.bookname as BookName,issusedate,returndate from books_borrowed as bb,books as b,members as m where bb.bookid = b.bookid and m.memid = NULL";
       PopulateTable.setTable(con, memberBorrowedJtable, sql);
}

public void calFine(){
     Calendar cal1 = Calendar.getInstance();
        Calendar cal2 = Calendar.getInstance();
        cal1.setTime(returnDate.getDate());
        cal2.setTime(new Date());
        
        // Get the represented date in milliseconds
        long milis1 = cal1.getTimeInMillis();
        long milis2 = cal2.getTimeInMillis();
        
        // Calculate difference in milliseconds
        long diff = milis2 - milis1;
        
        // Calculate difference in days
        long diffDays = diff / (24 * 60 * 60 * 1000);
        
        if(diffDays > 0){
            FineTf.setText(""+(diffDays*5));
        }
        else{
            FineTf.setText("0");
        }
}
    public BorrowBookFrame() {
        con = DataBaseConnection.getConnection();
        initComponents();
        IconSetter.setIcon(this);
        updateBorrowerTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        borrowBookNameTf = new javax.swing.JTextField();
        borrowEditionTf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        borrowAuthorTf = new javax.swing.JTextField();
        borrowBookidTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        borrowerBookIdLookupBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        borrowerIDLookup = new javax.swing.JButton();
        borrowerNameTf = new javax.swing.JTextField();
        borrowerIdTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        borrowIssuseDate = new com.toedter.calendar.JDateChooser();
        borrowReturnDate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        memberBorrowedJtable = new javax.swing.JTable();
        issuseBookBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        searchBorrowerTF = new javax.swing.JTextField();
        searchBorrowerBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BorrowerJtable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        returnBookEditionTf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        returnLookupBtn = new javax.swing.JButton();
        returnBooknameTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        returnBookId = new javax.swing.JTextField();
        FineTf = new javax.swing.JTextField();
        returnBorrowerNameTf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        calFineBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        returnBorrowerIdTF = new javax.swing.JTextField();
        confirmBtn = new javax.swing.JButton();
        returnissuseDate = new com.toedter.calendar.JDateChooser();
        returnDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Borrow Books - Library Management System");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Borrow Books Management", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 18))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Book Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14))); // NOI18N

        borrowBookNameTf.setEditable(false);

        borrowEditionTf.setEditable(false);

        jLabel4.setText("Author Name");

        jLabel1.setText("Book Id");

        jLabel2.setText("Book Name");

        borrowAuthorTf.setEditable(false);

        borrowBookidTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                borrowBookidTfKeyPressed(evt);
            }
        });

        jLabel3.setText("Edition");

        borrowerBookIdLookupBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lookupbook16.png"))); // NOI18N
        borrowerBookIdLookupBtn.setText("LookUp");
        borrowerBookIdLookupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowerBookIdLookupBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(borrowBookidTf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(borrowerBookIdLookupBtn)
                .addGap(6, 6, 6))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(borrowBookNameTf)
                    .addComponent(borrowEditionTf)
                    .addComponent(borrowAuthorTf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(borrowBookidTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrowerBookIdLookupBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(borrowBookNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(borrowEditionTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(borrowAuthorTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Borrower Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 3, 14))); // NOI18N

        jLabel9.setText("Date of Return");

        borrowerIDLookup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lookupuser16.png"))); // NOI18N
        borrowerIDLookup.setText("Look Up");
        borrowerIDLookup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowerIDLookupActionPerformed(evt);
            }
        });

        borrowerNameTf.setEditable(false);

        borrowerIdTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                borrowerIdTfKeyPressed(evt);
            }
        });

        jLabel8.setText("Date of Borrow");

        jLabel5.setText("Borrower ID");

        jLabel7.setText("Borrower Name");

        borrowIssuseDate.setDateFormatString("yyyy-MM-dd");

        borrowReturnDate.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(borrowIssuseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borrowReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(borrowerIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(borrowerIDLookup))
                            .addComponent(borrowerNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(borrowerIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrowerIDLookup))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(borrowerNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(borrowIssuseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(borrowReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        memberBorrowedJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(memberBorrowedJtable);

        issuseBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/issusebook16.png"))); // NOI18N
        issuseBookBtn.setText("Issue Book");
        issuseBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuseBookBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Books Borrowed");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(474, 474, 474)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(issuseBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(issuseBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Borrow Book For Students ", jPanel1);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 18))); // NOI18N

        searchBorrowerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search16.png"))); // NOI18N
        searchBorrowerBtn.setText("Search");
        searchBorrowerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBorrowerBtnActionPerformed(evt);
            }
        });

        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh16.png"))); // NOI18N
        refreshBtn.setText("Refresh Table");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchBorrowerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBorrowerBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshBtn)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBorrowerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBorrowerBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshBtn)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 18))); // NOI18N

        BorrowerJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(BorrowerJtable);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Borrower List", jPanel2);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Borrow Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 3, 14))); // NOI18N

        returnBookEditionTf.setEditable(false);

        jLabel16.setText("Date Of Issuse");

        returnLookupBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lookupbook16.png"))); // NOI18N
        returnLookupBtn.setText("Look up");
        returnLookupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnLookupBtnActionPerformed(evt);
            }
        });

        returnBooknameTF.setEditable(false);
        returnBooknameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBooknameTFActionPerformed(evt);
            }
        });

        jLabel13.setText("Borrower ID");

        jLabel17.setText("Last Date to Return");

        returnBookId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                returnBookIdKeyPressed(evt);
            }
        });

        FineTf.setEditable(false);

        returnBorrowerNameTf.setEditable(false);

        jLabel14.setText("Borrower Name");

        calFineBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fine16.png"))); // NOI18N
        calFineBtn.setText("Calculate Fine");
        calFineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calFineBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Book ID");

        jLabel12.setText("Book Name");

        jLabel18.setText("Fine");

        jLabel15.setText("Edition");

        returnBorrowerIdTF.setEditable(false);

        confirmBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/return16.png"))); // NOI18N
        confirmBtn.setText("Confirm Return");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        returnissuseDate.setDateFormatString("yyyy-MM-dd");
        returnissuseDate.setEnabled(false);
        returnissuseDate.setMinSelectableDate(new java.util.Date(-62135785722000L));

        returnDate.setDateFormatString("yyyy-MM-dd");
        returnDate.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(returnBookId)
                            .addComponent(returnBooknameTF)
                            .addComponent(returnBookEditionTf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(returnLookupBtn))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(confirmBtn)))
                .addGap(75, 75, 75)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel16))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(2, 2, 2)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(returnBorrowerIdTF)
                                .addComponent(returnBorrowerNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(returnissuseDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(returnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(FineTf, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calFineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(returnBorrowerIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(returnBorrowerNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(returnissuseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(returnBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnLookupBtn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(returnBooknameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(returnBookEditionTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(FineTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calFineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Return Book", jPanel3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnBooknameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBooknameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnBooknameTFActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
        new AdminFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void borrowerBookIdLookupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowerBookIdLookupBtnActionPerformed
        // TODO add your handling code here:
        try {
            if(!borrowBookidTf.getText().equals("")){
               ResultSet rs =  ManageBook.getBookInfo(con, borrowBookidTf.getText());
               if(rs.next()){
                    borrowBookNameTf.setText(rs.getString("bookname"));
                    borrowAuthorTf.setText(rs.getString("authorname"));
                    borrowEditionTf.setText(rs.getString("edition"));
                    
               }
               else {
                   /*borrowBookidTf.setText("");
                    borrowBookNameTf.setText("");
                    borrowAuthorTf.setText("");
                    borrowEditionTf.setText("");*/
                    resetBorrowForm();
                   JOptionPane.showMessageDialog(null, "Invalid Bookid");
               }
            }
            else{
                JOptionPane.showMessageDialog(null, "Enter a valid Bookid");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_borrowerBookIdLookupBtnActionPerformed

    private void borrowerIDLookupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowerIDLookupActionPerformed
        // TODO add your handling code here:
        try {
            if(!borrowerIdTf.getText().equals("")){
                String memiddata =borrowerIdTf.getText();
                int memid = Integer.parseInt(memiddata);
                sql = "SELECT bid AS IssuseId, b.bookid AS BookID, b.bookname AS BookName, issusedate, returndate FROM books_borrowed AS bb, books AS b WHERE bb.bookid = b.bookid AND bb.memid LIKE  '"+borrowerIdTf.getText()+"'";
                PopulateTable.setTable(con, memberBorrowedJtable, sql);
               ResultSet rs =  ManageBorrow.getBorrowerInfo(con, memid);
               if(rs.next()){
                    borrowerNameTf.setText(rs.getString("memname"));
                    Date date = new Date();
                    borrowIssuseDate.setDate(date);
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(date);
                    cal.add(Calendar.DATE, 10); // add 10 days
                    date = cal.getTime();
                    borrowReturnDate.setDate(date);
               }
               else {
                    resetBorrowForm();
                   JOptionPane.showMessageDialog(null, "Invalid Member");
               }
            }
            else{
                JOptionPane.showMessageDialog(null, "Enter a valid Member Id");
            }
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter A valid Member ID");
        }
        catch (Exception e) {
        }
        
    }//GEN-LAST:event_borrowerIDLookupActionPerformed

    private void issuseBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuseBookBtnActionPerformed
        // TODO add your handling code here:
        try {
            //ensure user has enter the fields
            if(!borrowBookNameTf.getText().equals("") && !borrowerNameTf.getText().equals("")){
                
                
                if(!ManageBorrow.canBorrow(con, borrowerIdTf.getText())){
                    JOptionPane.showMessageDialog(null, "Reached Maximum Issuse Limit");
                    resetBorrowForm();
                    return;
                }
                if(!ManageBook.isAvaialable(con, borrowBookidTf.getText())){
                    
                    JOptionPane.showMessageDialog(null, "Book Not Available");
                    resetBorrowForm();
                    return;
                }
                
                ArrayList al = new ArrayList();
                al.add(borrowBookidTf.getText());
                al.add(borrowerIdTf.getText());
                al.add( ( (JTextField)borrowIssuseDate.getDateEditor().getUiComponent() ).getText() );
                al.add(( (JTextField)borrowReturnDate.getDateEditor().getUiComponent() ).getText() );
                
                    
                if(ManageBorrow.issuseBook(con, al)){
                    
                sql = "select bid as IssuseId,b.bookid as BookID,b.bookname as BookName,issusedate,returndate from books_borrowed as bb,books as b,members as m where bb.bookid = b.bookid and m.memid = "+borrowerIdTf.getText();
                PopulateTable.setTable(con, memberBorrowedJtable, sql);
                updateBorrowerTable();
                    JOptionPane.showMessageDialog(null, "Book Issused Sucessfully");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Book Not Issused");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid BookId or BorrowerID Fields");
            }
            
        } catch (Exception e) {
        }
        resetBorrowForm();
    }//GEN-LAST:event_issuseBookBtnActionPerformed

    private void returnLookupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnLookupBtnActionPerformed
        // TODO add your handling code here:
        
        try {
            if(!returnBookId.getText().equals("")){
                    if(ManageBook.isIssused(con,returnBookId.getText())){
                            ResultSet rs = ManageBorrow.getIssusedBook(con, returnBookId.getText());
                            while(rs.next()){
                                returnBooknameTF.setText(rs.getString("BookName"));
                                returnBookEditionTf.setText(rs.getString("edition"));
                                returnBorrowerIdTF.setText(rs.getString("memid"));
                                returnBorrowerNameTf.setText(rs.getString("memname"));
                                returnissuseDate.setDate(rs.getDate("issusedate"));
                                returnDate.setDate(rs.getDate("returndate"));
                                calFine();
                            }
                    }
                    else{
                        resetReturnForm();
                        JOptionPane.showMessageDialog(null, "Book is not issused");
                    }
                }
                else{
                resetReturnForm();
                    JOptionPane.showMessageDialog(null, "Enter Valid BookId");
                }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_returnLookupBtnActionPerformed

    private void calFineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calFineBtnActionPerformed
        // TODO add your handling code here:
        calFine();
    }//GEN-LAST:event_calFineBtnActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        try {
            if(!returnBookId.getText().equals("")){
                if(ManageBorrow.returnBook(con, returnBookId.getText())){
                    resetReturnForm();
                updateBorrowerTable();
                    JOptionPane.showMessageDialog(null, "Book Returned Successfully");
                }
                else{
                    resetReturnForm();
                    JOptionPane.showMessageDialog(null, "Book Not Returned ");
                }
            }
            else{
                    JOptionPane.showMessageDialog(null, "Book Returned Successfully");
                JOptionPane.showMessageDialog(null, "Enter a bookid");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void searchBorrowerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBorrowerBtnActionPerformed
        // TODO add your handling code here:
        try {
            if(!searchBorrowerTF.getText().equals("")){
                updateBorrowerTable();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_searchBorrowerBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        updateBorrowerTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void returnBookIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_returnBookIdKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            try {
                if(!returnBookId.getText().equals("")){
                        if(ManageBook.isIssused(con,returnBookId.getText())){
                                ResultSet rs = ManageBorrow.getIssusedBook(con, returnBookId.getText());
                                while(rs.next()){
                                    returnBooknameTF.setText(rs.getString("BookName"));
                                    returnBookEditionTf.setText(rs.getString("edition"));
                                    returnBorrowerIdTF.setText(rs.getString("memid"));
                                    returnBorrowerNameTf.setText(rs.getString("memname"));
                                    returnissuseDate.setDate(rs.getDate("issusedate"));
                                    returnDate.setDate(rs.getDate("returndate"));
                                    calFine();
                                }
                        }
                        else{
                            resetReturnForm();
                            JOptionPane.showMessageDialog(null, "Book is not issused");
                        }
                    }
                    else{
                    resetReturnForm();
                        JOptionPane.showMessageDialog(null, "Enter Valid BookId");
                    }

            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_returnBookIdKeyPressed

    private void borrowBookidTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_borrowBookidTfKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                        try {
                if(!borrowBookidTf.getText().equals("")){
                   ResultSet rs =  ManageBook.getBookInfo(con, borrowBookidTf.getText());
                   if(rs.next()){
                        borrowBookNameTf.setText(rs.getString("bookname"));
                        borrowAuthorTf.setText(rs.getString("authorname"));
                        borrowEditionTf.setText(rs.getString("edition"));

                   }
                   else {
                       /*borrowBookidTf.setText("");
                        borrowBookNameTf.setText("");
                        borrowAuthorTf.setText("");
                        borrowEditionTf.setText("");*/
                        resetBorrowForm();
                       JOptionPane.showMessageDialog(null, "Invalid Bookid");
                   }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Enter a valid Bookid");
                }

            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_borrowBookidTfKeyPressed

    private void borrowerIdTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_borrowerIdTfKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                try {
                if(!borrowerIdTf.getText().equals("")){
                    String memiddata =borrowerIdTf.getText();
                    int memid = Integer.parseInt(memiddata);
                    sql = "SELECT bid AS IssuseId, b.bookid AS BookID, b.bookname AS BookName, issusedate, returndate FROM books_borrowed AS bb, books AS b WHERE bb.bookid = b.bookid AND bb.memid LIKE  '"+borrowerIdTf.getText()+"'";
                    PopulateTable.setTable(con, memberBorrowedJtable, sql);
                   ResultSet rs =  ManageBorrow.getBorrowerInfo(con, memid);
                   if(rs.next()){
                        borrowerNameTf.setText(rs.getString("memname"));
                        Date date = new Date();
                        borrowIssuseDate.setDate(date);
                        Calendar cal = Calendar.getInstance();
                        cal.setTime(date);
                        cal.add(Calendar.DATE, 10); // add 10 days
                        date = cal.getTime();
                        borrowReturnDate.setDate(date);
                   }
                   else {
                        resetBorrowForm();
                       JOptionPane.showMessageDialog(null, "Invalid Member");
                   }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Enter a valid Member Id");
                }

            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Enter A valid Member ID");
            }
            catch (Exception e) {
            }

        }
    }//GEN-LAST:event_borrowerIdTfKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrowBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrowBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrowBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrowBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrowBookFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BorrowerJtable;
    private javax.swing.JTextField FineTf;
    private javax.swing.JTextField borrowAuthorTf;
    private javax.swing.JTextField borrowBookNameTf;
    private javax.swing.JTextField borrowBookidTf;
    private javax.swing.JTextField borrowEditionTf;
    private com.toedter.calendar.JDateChooser borrowIssuseDate;
    private com.toedter.calendar.JDateChooser borrowReturnDate;
    private javax.swing.JButton borrowerBookIdLookupBtn;
    private javax.swing.JButton borrowerIDLookup;
    private javax.swing.JTextField borrowerIdTf;
    private javax.swing.JTextField borrowerNameTf;
    private javax.swing.JButton calFineBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JButton issuseBookBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable memberBorrowedJtable;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField returnBookEditionTf;
    private javax.swing.JTextField returnBookId;
    private javax.swing.JTextField returnBooknameTF;
    private javax.swing.JTextField returnBorrowerIdTF;
    private javax.swing.JTextField returnBorrowerNameTf;
    private com.toedter.calendar.JDateChooser returnDate;
    private javax.swing.JButton returnLookupBtn;
    private com.toedter.calendar.JDateChooser returnissuseDate;
    private javax.swing.JButton searchBorrowerBtn;
    private javax.swing.JTextField searchBorrowerTF;
    // End of variables declaration//GEN-END:variables
}
